feedback_data = [
    {"rating": 5, "comment": "The teacher explains concepts very clearly and is very helpful."},
    {"rating": 4, "comment": "Good teaching but sometimes lectures are too fast."},
    {"rating": 2, "comment": "Hard to understand topics and not enough examples."},
    {"rating": 3, "comment": "Average teaching, communication could be better."},
    {"rating": 5, "comment": "Very engaging and interactive classes."},
    {"rating": 1, "comment": "Teacher is rude and does not listen to students."},
    {"rating": 4, "comment": "Explains well but sometimes goes off-topic."},
    {"rating": 2, "comment": "Pace is too fast and difficult to follow."},
    {"rating": 5, "comment": "Best teacher, very supportive and helpful."},
    {"rating": 3, "comment": "Course is difficult but teacher tries to help."},

    {"rating": 4, "comment": "Good communication and clear explanations."},
    {"rating": 2, "comment": "Not engaging, lectures are boring."},
    {"rating": 5, "comment": "Makes complex topics simple and easy."},
    {"rating": 1, "comment": "Does not explain properly."},
    {"rating": 3, "comment": "Okay teaching but needs improvement in clarity."},
    {"rating": 5, "comment": "Very interactive and fun classes."},
    {"rating": 4, "comment": "Good but sometimes too fast."},
    {"rating": 2, "comment": "Difficult to understand due to poor explanation."},
    {"rating": 1, "comment": "Very rude behavior and not supportive."},
    {"rating": 5, "comment": "Excellent teaching and very helpful."},

    {"rating": 3, "comment": "Average experience, nothing special."},
    {"rating": 4, "comment": "Good teaching style but needs more examples."},
    {"rating": 2, "comment": "Lectures are too fast and confusing."},
    {"rating": 5, "comment": "Very clear explanation and engaging teaching."},
    {"rating": 1, "comment": "Teacher is not friendly."},
    {"rating": 3, "comment": "Communication could improve."},
    {"rating": 4, "comment": "Good explanation but sometimes boring."},
    {"rating": 2, "comment": "Not interactive and difficult."},
    {"rating": 5, "comment": "Very supportive and motivating teacher."},
    {"rating": 1, "comment": "Does not answer questions properly."},

    {"rating": 5, "comment": "Amazing teaching style and very engaging."},
    {"rating": 4, "comment": "Good but lectures feel rushed."},
    {"rating": 2, "comment": "Too difficult and not clear."},
    {"rating": 3, "comment": "Okay but needs improvement."},
    {"rating": 5, "comment": "Explains everything in a simple way."},
    {"rating": 1, "comment": "Very poor communication."},
    {"rating": 4, "comment": "Nice teaching but sometimes too fast."},
    {"rating": 2, "comment": "Not clear explanation."},
    {"rating": 5, "comment": "Very engaging and interesting lectures."},
    {"rating": 3, "comment": "Neutral experience."},

    {"rating": 4, "comment": "Good teacher but needs better pacing."},
    {"rating": 2, "comment": "Boring lectures and not interactive."},
    {"rating": 5, "comment": "Excellent and very clear teaching."},
    {"rating": 1, "comment": "Rude and not helpful."},
    {"rating": 3, "comment": "Average, nothing impressive."},
    {"rating": 4, "comment": "Clear teaching but a bit fast."},
    {"rating": 2, "comment": "Difficult and confusing lectures."},
    {"rating": 5, "comment": "Very helpful and supportive."},
    {"rating": 1, "comment": "Bad teaching style."},
    {"rating": 5, "comment": "One of the best teachers, very engaging."}
]